spring:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: INFO
    com.jinforce: DEBUG